### PR TITLE
Add new logo and reorganize the folders

### PR DESCRIPTION
**Pull request by rradczewski**
@khamiltonuk sent me the current logo as I couldn't find it in this repository. 

This PR removes the old logo files (6c89276, can undo and reorganize them if y'all would rather keep them around in the repo) and adds the new logo with a few different formats (using a [`Makefile`](https://github.com/codebar/assets/compare/master...rradczewski:add_new_logo?short_path=22fc8c6#diff-c89ca6eb27477cc5d332e324e4322306) so the derived formats can be generated automatically).

I further moved the `mind-the-code` illustrations to their own folder in `illustrations/`.

### CODE REVIEW

**Comment by matyikriszta** [comment]
hi @rradczewski I know this PR has been merged in but I have one request: can we add the instructions on how to use the Makefile into the README?

**Comment by rradczewski** [comment]
Hi @matyikriszta, not sure I understand as @KimberleyCook closed this PR without merging it. 

I'd happily adapt the Makefile for the repo as it is right now if that'd be useful

**Comment by KimberleyCook** [comment]
Sorry I should've commented, another PR moved all the old logos to a folder called archive. COuld we do another PR adding the Makefile work please?

**Comment by rradczewski** [comment]
Sure, I'll take care of that over the weekend. The Makefile is already [documented](https://github.com/codebar/assets/blob/441b840a28bbad5b9d4e790627d7bd4dada23355/logo/Makefile), I'd further add some usage explanation to the top-level `README` if that's alright 😊

**Comment by matyikriszta** [comment]
@rradczewski sorry Raimo, I didin't realize this PR was closed without merge, but that is what I meant, adding the instructions to the top level README once the new Makefile is added.

**Pull request closed without merging**
