### PR TITLE
feat: add zip file containing indesign file and pdf of kent codebar c…

### PR DESCRIPTION
**Pull request by MMasey**
Adds a zip file containing indesign file and pdf of kent codebar chapter flyer.

### CODE REVIEW

**Comment by KimberleyCook** [comment]
@MMasey thanks for this, do these files need to be in a zip folder?

**Comment by MMasey** [comment]
Potentially not, the indesign file contains some links to images that are dependent on the folder structure so i figured it would be better to include all the files together (assuming someone just downloads the individual indesign file as opposed to cloning down the repo). I could take out the pdf version but that one is just setup for the Kent chapter. I'm happy to re-arrange as needed.

**Comment by khamiltonuk** [comment]
Hi Mike @MMasey , I think I have made a pull request #9 with the same assets outside of a zip file, as we used the same design for the Berlin codebar 😃😃

**Comment by MMasey** [comment]
Nice one, thanks @khamiltonuk. And I agree about your feedback in regards to the image :)

**Comment by KimberleyCook** [comment]
@MMasey what is the status of this PR?

**Comment by MMasey** [comment]
Hey @KimberleyCook I wonder if this one should be closed in favour of @khamiltonuk's PR #9

**Pull request closed without merging**
